from .greetings import Greetings
from .farewells import Farewells
from .autovoice import AutoVoice
from .manager import Manager
from .votes import Votes
from .vkmemes import VkMemes
from .nickcolors import NickColors
from .premium import Premium
from .mutes import Mutes
from .tickets import Tickets
from .profiles import Profiles
from .chatgpt import ChatGPT
from .minecraft import Minecraft
from .simplechatgpt import SimpleChatGPT